export const GET_ALL_QUESTION = "http://nativesmile.topica.edu.vn/modules/index.php/api/H2472/getAllThreadInCourse?page="
export const GET_ALL_QUESTION_SUCCESS = "GET_ALL_QUESTION_SUCCESS"
export const GET_ALL_QUESTION_FAILED = "GET_ALL_QUESTION_FAILED"
export const GET_MY_QUESTION = "http://nativesmile.topica.edu.vn/modules/index.php/api/H2472/getMyThreadInCourse?page="
export const GET_MY_QUESTION_SUCCESS = "GET_MY_QUESTION_SUCCESS"
export const GET_MY_QUESTION_FAILED = "GET_MY_QUESTION_FAILED"